### ISSUE TITLE
Launch Barrier

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#12]
After installing, I pointed my browser to the relevant IP and it returned the text of a PHP file, which began: 

```
<?php
/**
 * CodeIgniter
 *
`
```

**It ended with:**

```
/*
 * --------------------------------------------------------------------
 * LOAD THE BOOTSTRAP FILE
 * --------------------------------------------------------------------
 *
 * And away we go...
 */
require_once BASEPATH.'core/CodeIgniter.php';
```

So the Login page didn't appear. 

This COULD be a problem with the fact that doing a "clean" install of everything was difficult and I may not have done it cleanly enough!

**Comment by dcaud** [comment]
I'm trying to load FruxePi on a fresh install of Debian Lite. I'll provide an update in a while.

**Comment by dcaud** [comment]
I didn't have any luck following the instructions after a fresh install of Debian Lite.

When I went to my IP I was redirected to  "http://192.168.2.19/login" but the only thing that appeared was:

```
Not Found
The requested URL /login was not found on this server.

```

Any ideas?

**Comment by dcaud** [comment]
I've confirmed that PHP is running by placing a test.php file in /var/www/html with the following:
 
```
<?php 
  phpinfo(); 
?>
```

Pointing my browser to "http://192.168.2.19/test.php" results in the expected page being served with details of the PHP installation.

**Comment by dcaud** [comment]
The frx_db databse seems to be running in mysql, because when I do, e.g., these things:

```
sudo mysql -u root -p

USE frx_db;
SELECT * FROM climate_history;
```

I get this:

+----+---------------------+-------------+----------+
| id | date_time           | temperature | humidity |
+----+---------------------+-------------+----------+
|  1 | 2018-10-18 00:00:00 | 25          | 75       |
|  2 | 2018-10-18 01:00:00 | 27          | 88       |
|  3 | 2018-10-18 02:00:00 | 26          | 84       |
|  4 | 2018-10-18 03:00:00 | 26          | 80       |
|  5 | 2018-10-18 04:00:00 | 25          | 77       |
|  6 | 2018-10-18 05:00:00 | 26          | 78       |
|  7 | 2018-10-18 06:00:00 | 25          | 75       |
|  8 | 2018-10-18 07:00:00 | 27          | 76       |
|  9 | 2018-10-18 08:00:00 | 28          | 80       |
| 10 | 2018-10-18 09:00:00 | 25          | 75       |
| 11 | 2018-10-18 10:00:00 | 27          | 81       |
| 12 | 2018-10-18 11:00:00 | 28          | 84       |
| 13 | 2018-10-18 12:00:00 | 28          | 83       |
| 14 | 2018-10-18 13:00:00 | 28          | 82       |
| 15 | 2018-10-18 14:00:00 | 29          | 88       |
| 16 | 2018-10-18 15:00:00 | 30          | 90       |
| 17 | 2018-10-18 16:00:00 | 25          | 75       |
| 18 | 2018-10-18 17:00:00 | 25          | 80       |
| 19 | 2018-10-18 18:00:00 | 25          | 79       |
| 20 | 2018-10-18 19:00:00 | 25          | 78       |
| 21 | 2018-10-18 20:00:00 | 24          | 77       |
| 22 | 2018-10-18 21:00:00 | 24          | 74       |
| 23 | 2018-10-18 22:00:00 | 22          | 73       |
| 24 | 2018-10-18 23:00:00 | 23          | 72       |
+----+---------------------+-------------+----------+
24 rows in set (0.00 sec)
```

**Comment by dcaud** [comment]
I just did a fresh install of the full Raspbian and followed the FruxePi install instructions. I came up emty again. Here's what I got when I went to the relevant IP:

```
Not Found
The requested URL /FruxePi-master/login was not found on this server.

Apache/2.4.25 (Raspbian) Server at 192.168.2.19 Port 80
```

I'm STUCK!

**Comment by fruxefarms** [comment]
What is your www path? eg `/var/www/html/` 

The error is showing a strange URL `/FruxePi-master/login`.

**Comment by dcaud** [comment]
I think the original error that I had when I started this Issue was resolved by a fresh install of Raspbian and a new attempt to install FruxePi. However, now the problem is similar (notice the change in the path):

```
Not Found
The requested URL /login was not found on this server.

Apache/2.4.25 (Raspbian) Server at 192.168.2.19 Port 80

```

My current www path is:

```
$ pi@pp:/var/www/html
```

**Comment by dcaud** [comment]
And here is the directory structure inside `/var/www/html`:

```
/var/www/html
├── actions
├── application
│   ├── cache
│   ├── config
│   ├── controllers
│   ├── core
│   ├── helpers
│   ├── hooks
│   ├── language
│   │   └── english
│   ├── libraries
│   ├── logs
│   ├── models
│   ├── third_party
│   └── views
│       ├── auth
│       │   └── email
│       ├── core
│       ├── crop
│       ├── dashboard
│       ├── errors
│       │   ├── cli
│       │   └── html
│       ├── technical
│       └── user
├── assets
│   ├── css
│   │   └── bootstrap
│   ├── img
│   ├── js
│   │   └── bootstrap
│   └── webfonts
├── db
├── docs
│   └── img
└── system
    ├── core
    │   └── compat
    ├── database
    │   └── drivers
    │       ├── cubrid
    │       ├── ibase
    │       ├── mssql
    │       ├── mysql
    │       ├── mysqli
    │       ├── oci8
    │       ├── odbc
    │       ├── pdo
    │       │   └── subdrivers
    │       ├── postgre
    │       ├── sqlite
    │       ├── sqlite3
    │       └── sqlsrv
    ├── fonts
    ├── helpers
    ├── language
    │   └── english
    └── libraries
        ├── Cache
        │   └── drivers
        ├── Javascript
        └── Session
            └── drivers
```

**Comment by dcaud** [comment]
Hello. You can ignore this issue now! The docker-fied installation process worked! Thank you so much!!!

**Comment by fruxefarms** [comment]
Great! I’m glad to hear! How is the app operating? You were a big help in getting this all sorted. A big thank you from me also!

**Comment by dcaud** [comment]
I have navigated around the user interface and all seems good. I'll be connecting devices soon and will let you know about the sensors and control. 

I've also gotten a feel for how Code Ignitor/PHP/SQL/Python is doing the work. As I get more proficient, I will hopefully be able to make some code suggestions -- like coding a setting to menu button to switch from Celsius to Fahrenheit -- which actually seems like a good amount of work: 1) Put the selection on the settings page; 2) write a conversion equation [(°C × 9/5) + 32 = °F]; change the UI in a few places (the banner, the chart, and the setting page (e.g., for the fan control). Once I get the basics, I can try to help by forking.

Thanks again.

**Comment by fruxefarms** [comment]
Good news - I have been working on the Temperature conversion part. Hopefully I will have that pushed this coming week.

**Comment by dcaud** [comment]
Excellent! Maybe I'll work on a servo control interface (I have a need to
use a servo).

**Comment by fruxefarms** [comment]
Oh I like the idea of a servo :)
