### ISSUE TITLE
Celcius to Farenheit conversion

### ISSUE THREAD

**Issue by jkissner** [fruxefarms/FruxePi#13]
Self-explanatory.  I don't mind the Celcius but I know others who will be looking would prefer Fahrenheit.

**Comment by fruxefarms** [comment]
True, we can't forget our American friends! An easy addition. Will add this to the roadmap.

**Comment by dcaud** [comment]
I too would like Fahrenheit!

**Comment by fruxefarms** [comment]
There is now an option in Climate Settings to toggle the temperature from Celsius to Fahrenheit.
