### ISSUE TITLE
Technical>>lights menu PHP error Light relay not working

### ISSUE THREAD

**Issue by jkissner** [fruxefarms/FruxePi#15]
When opening and modifying the lights settings. I get the following errors. The Relay never fires.  I have tested the relay and GPIO config manually and it works. 

A PHP Error was encountered
Severity: Notice

Message: Undefined offset: 0

Filename: models/Lights_model.php

Line Number: 161

Backtrace:

File: /var/www/html/application/models/Lights_model.php
Line: 161
Function: _error_handler

File: /var/www/html/application/controllers/Sensors.php
Line: 171
Function: getLightsStatus

File: /var/www/html/index.php
Line: 315
Function: require_once

**Comment by fruxefarms** [comment]
I have this fix and will update shortly.

**Comment by jkissner** [comment]
I seem to have fixed this with the following:
sudo apt-get install rpi.gpio

I also installed:
sudo apt-get install git-core
 cd ~
 git clone git://git.drogon.net/wiringPi
 cd wiringPi
 git pull origin
 sudo ./build

this simply lets me look at "gpio readall"

**Comment by fruxefarms** [comment]
Hmm, that's interesting for a number of reasons. 1. I may have neglected to add wiring_pi as a necessary dependency in documentation. 2. That error has been occurring on the demo site due to an out of bounds array, but now I'm wondering what data that callback is providing. Will investigate!

**Comment by fruxefarms** [comment]
Adding WiringPi instructions to the docs. That was definitely the issue. Thanks!
