### ISSUE TITLE
What are the proper MYSQL database credentials?

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#16]
I'm referring to this line in the documentation:

**Make sure that the following fields are set properly with your MYSQL database credentials.**
```
'hostname' => 'localhost:3306',
'username' => 'frxpi',
'password' => 'password',
'database' => 'frx_db',
```
I merely changed 'password' to match what I used elsewhere. Do I need to update any of these other variables?

**Comment by jkissner** [comment]
Only if you changed them in the Database setup commands.
