### ISSUE TITLE
PHP error after deleting default crop

### ISSUE THREAD

**Issue by jkissner** [fruxefarms/FruxePi#18]
A PHP Error was encountered
Severity: Notice

Message: Undefined offset: 0

Filename: models/Crop_model.php

Line Number: 96

Backtrace:

File: /var/www/html/application/models/Crop_model.php
Line: 96
Function: _error_handler

File: /var/www/html/application/models/Crop_model.php
Line: 45
Function: getCrop

File: /var/www/html/application/controllers/Dashboard.php
Line: 48
Function: cropInfo

File: /var/www/html/index.php
Line: 315
Function: require_once

**Comment by fruxefarms** [comment]
Addressed this error with latest commit!
