### ISSUE TITLE
Missing minor step in install code

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#2]
After running `sudo apt-get install phpmyadmin -y` a dialog box appeared that looked like this:

![image](https://user-images.githubusercontent.com/28665108/53756898-53910c80-3e88-11e9-95c3-3801d9e06410.png)

I presume the correct thing to do was to hit ENTER, which selects apache2.

Adding those instructions may help.

**Comment by jkissner** [comment]
This will only show if you have Lighttpd install with Apache. In the instructions, it's assuming you have only the default Apache installed.

**Comment by fruxefarms** [comment]
Good feedback - agree! Will incorporate these steps in the README.
