### ISSUE TITLE
lights are not following schedule

### ISSUE THREAD

**Issue by jkissner** [fruxefarms/FruxePi#20]
LIghts do not turn on and off with the schedule.  schedule script doesn't seem to write to cron

**Comment by fruxefarms** [comment]
Just curious if the following line is uncommented or not in the crontab file:
```
0 1 * * * python /var/www/html/actions/fruxepi.py lights -ON 15
0 1 * * * python /var/www/html/actions/fruxepi.py lights -OFF 15
```
In the installation README they are commented out by default.
