### ISSUE TITLE
Reorder IP address instructions given new Docker install procedure

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#22]
At the bottom of https://github.com/fruxefarms/FruxePi#launch-app, would it make sense to add:

```
How do I find my Pi's IP address? 
[Check out the following link](https://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup/finding-your-pis-ip-address)
```

This had me stumped for a while (because of the quantity of IP address-looking numbers with `sudo ifconfig`).

Or maybe it would be better to just put a link in the new docker-install section to the section created previously which has details about adding users and turning on sensors.

**Comment by fruxefarms** [comment]
Agree! I think the docker deployment will be the main way forward. Must update those docs!
