### ISSUE TITLE
Displayed TimeZone Doesn't Match Raspberry Pi Machine's TimeZone

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#23]
I've set my local machine to use the timezone in which I live. However, the dashboard is off, presumably because it is using UTC. Running `date` inside the docker container is different than running `date` at the `pi@raspberrypi:~ $` prompt.

I tried to change it with this:

```
sudo docker exec -it frxpi-APACHE bash
echo Europe/Stockholm >/etc/timezone && \
dpkg-reconfigure -f noninteractive tzdata
```

and then this:

```
sudo docker exec -it frxpi-MYSQL bash
echo Europe/Stockholm >/etc/timezone && \
dpkg-reconfigure -f noninteractive tzdata
```

Instead of "Europe/Stockholm" you'd enter your timezone from [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

Now, the dates match inside the docker containers and the host...however, the dashboard still displays the wrong date.

I guess, ideally this would be done via Docker. Ideas about how to do this in Docker-Compose are [here](https://www.ivankrizsan.se/2015/10/31/time-in-docker-containers/).

**Comment by fruxefarms** [comment]
I think this is simply a matter of syncing Docker Apache timezone with the RPI. If you SSH into the container I believe you can change it. Nevertheless, I will work on this fix ASAP.

**Comment by fruxefarms** [comment]
Ahh, nevermind. I saw you tried this! Will do some testing.

**Comment by fruxefarms** [comment]
I can confirm if you add this to the Dockerfile and then rebuild you can adjust to your timezone:
```
ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```
Will be adding this to the master soon.

**Comment by fruxefarms** [comment]
I think this has been sorted out in the latest commit.

**Comment by dcaud** [comment]
The time stamp at the bottom of my chart on the dashboard page still doesn't reflect my timezone. I did, however, set the ENV variable in the dockerfile as instructed. Hmm.

**Comment by fruxefarms** [comment]
I believe this is an issue with setting the time in the MYSQL docker container. I may have found a solution. Just testing.

**Comment by fruxefarms** [comment]
I believe this has been corrected in the latest commit. There is also no need to manually set the timezone anymore. It will adjust based on whichever timezone the Pi has configured at runtime.

**Comment by dcaud** [comment]
The "Last Update" at the bottom of the dashboard correct now seems correct (it is showing about 15 minutes ago after a refresh).
