### ISSUE TITLE
Procedure for removing docker-ized Fruxe-Pi before reinstallation

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#25]
Below is what I did to remove the prior beta version of Fruxe-Pi in preparation for installing the newer version. I'm not totally sure ALL of this is needed, but thought I'd document what I did. Maybe something like this could be added to the documents at some point.

List the docker containers:
```
sudo docker ps
```
Stop and then remove the dockers, by ID, that showed up in the list above:
```
sudo docker stop [insert docker ID here, without brackets]
sudo docker [insert docker ID here, without brackets]
```
Remove the volumes that stored the database (you may be able to keep this, to keep the data you collected up to this point)

List the volumes:
```
sudo docker volume ls
```
Remove the volume (assuming the name is docker_db_data):
```
sudo docker volume rm docker_db_data
```
Remove the folder where the `git` downloads the docker into:
```
cd
sudo rm -r FruxePi
```

**Comment by fruxefarms** [comment]
This is a great idea! Another command I use to wipe out the old docker images and volumes is `docker system prune -a`

**Comment by dcaud** [comment]
Sounds good. Here is the list of commands that I think work for a reinstallation...I'm pasting here so I can copy later, as needed.

(the "-f" on `sudo docker system prune -f` should remove the confirmation dialog)

```
sudo docker stop frxpi-APACHE
sudo docker stop frxpi-PHPMYADMIN
sudo docker stop frxpi-MYSQL
sudo docker system prune -f
sudo docker volume rm docker_db_data
sudo rm -r FruxePi
git clone https://github.com/fruxefarms/FruxePi.git
cd FruxePi
sudo bash install.sh
```

**Comment by fruxefarms** [comment]
Perfect! I just ran through this and it all works great! Will incorporate into the documentation as "Upgrading"
