### ISSUE TITLE
Live Camera View Not Working

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#26]
Technical » Camera » Take Photo works wonderfully. However, clicking on the camera icon on the dashboard page just pulls up the stock image.

**Comment by fruxefarms** [comment]
The Camera is now updating properly. The file was improperly linked. However, enabling/disabling the Camera is not editing the crontab file. Until I hunt that down you will have to uncomment this line manually using `sudo crontab -u www-data -e`.
```
#* * * * * sudo /var/www/html/actions/fruxepi.py camera -crop
```

**Comment by fruxefarms** [comment]
This has been fixed in the latest commit!
