### ISSUE TITLE
Light schedule countdown issue/feature request

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#27]
This is kind of a feature request/change in the UI:

The "__ hours, __ minutes until dark" at the top of the page is a bit confusing to me. I was thinking this had to do with sunrise and sunset (and was connected to the timezone bug I was trying to test)...but that assumption was wrong. The "until dark" is supposed to be a countdown to when the lights will be turned on (or off). This is based on the schedule settings for the lights. 

I think a change in the *wording* of the UI would be helpful. Something like this:

 "__ hours, __ minutes until lights **turn on**" (or "off")

It is GREAT that this text only shows up when the light "sensor" is enabled. In my case, we don't have grow lights...so I think it may make sense for the "Enable / Disable Probe" default status to be "off." The same goes for all other sensors...except the temperature/humidity sensor.

**Comment by fruxefarms** [comment]
Great idea! I think that is much clearer.
