### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#28]
The below pops up in the web browser, after I enter the default username and password in the login screen. This happened just after a fresh (re)installation that just finished minutes ago -- presumably after the latest commit.

```
FruxePi » A Database Error Occurred
Error Number: 1146

Table 'frx_db.users' doesn't exist

SELECT `email`, `email`, `id`, `password`, `active`, `last_login` FROM `users` WHERE `email` = 'hello@fruxe.co' ORDER BY `id` DESC LIMIT 1

Filename: models/Ion_auth_model.php

Line Number: 1038
```

**Comment by dcaud** [comment]
Hmm. Maybe ignore the above. I did a fresh re-install and didn't get an error!

**Comment by fruxefarms** [comment]
I think this is an install script error. Something failed and the MYSQL container wasn't created. The install script needs some definite refinement and order.

**Comment by dcaud** [comment]
Well, I just re-installed and got the same message at the top of this thread. I'll try again!

**Comment by dcaud** [comment]
Yep. The same thing happened after a fresh re-installation.

**Comment by dcaud** [comment]
I just re-installed and now it works!
