### ISSUE TITLE
Missing detailed instructions under Codeigniter Config 

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#3]
Under Codeigniter Config there is the following instruction:

**Open the Codeigniter database.php config file in the /frx-pi/application/config/ folder**

However, it was unclear to me how to do that. Here's what worked for me:

```
$ cd /var/www/html/application/config
$ nano database.php
```
Then scroll to the bottom of the file.

**Comment by fruxefarms** [comment]
A nice step to add! Will do!
