### ISSUE TITLE
Chart still not updating

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#31]
I just did a fresh install and the chart isn't updating with new data. Are you still working on this?

**Comment by dcaud** [comment]
I think there was a problem with the date/time stamp format (and more) with the code inside update_history. The below seems to work:

```
def update_history(data):
    #print(data)
    data['timestamp'] = strftime("%Y-%m-%d %H:%M:%S")
    dbData = [data['timestamp'], data['temperature'], data['humidity']]
    print(dbData)
    db = pymysql.connect(host, user, password, database)
    cursor = db.cursor()

    try:
        cursor.execute("INSERT INTO climate_history (date_time, temperature, humidity) VALUES(%s, %s, %s)", dbData)        
        db.commit()
        print("History Data Updated!")
    except:
        print("Database Error!")
        db.rollback()
        db.close()
```
The above gets data already averaged over the prior hour (I think) from fetch_history(). [I think rounding temp and humidity may still be needed.]

Also, I needed to revise the cron file here:

```
sudo docker exec -it frxpi-APACHE bash
sudo crontab -u www-data -e
```

to this:

```
# FruxePi
* * * * * sudo /var/www/html/actions/fruxepi.py update -growdata
* * * * * sudo /var/www/html/actions/fruxepi.py update -chart
0 1 * * * sudo /var/www/html/actions/fruxepi.py maint -cleanup
* * * * * sudo /var/www/html/actions/fruxepi.py camera -crop
#0 1 * * * sudo /var/www/html/actions/fruxepi.py lights -ON 15
#0 1 * * * sudo /var/www/html/actions/fruxepi.py lights -OFF 15
#0 * * * * sudo /var/www/html/actions/fruxepi.py fan -RUN 17 10
#11 11 * * * sudo /var/www/html/actions/fruxepi.py pump -RUN 15 5
```
(Note that I changed the frequency to once a minute, to more easily see the updates)

and then:
`
sudo service cron reload
`

**Comment by fruxefarms** [comment]
I think all is working. I would suggest a completely fresh install and run  `sudo docker system prune -f -a --volumes`

**Comment by dcaud** [comment]
I did a fresh install and the chart still doesn't update.
