### ISSUE TITLE
Language Change on Light, Fan, etc "Probes"

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#32]
On the Technical -> Lights page, e.g., there is a toggle button for "Enable/Disable Probe." I think removing "Probe" for Lights (and Fans and Pump) would be more intuitive -- because these are not exactly probes. 

Removing the word "Probe" from all the button labels might make the most sense (and be the easiest).

**Comment by fruxefarms** [comment]
Agree! Updated in latest commit.
