### ISSUE TITLE
UI Language in Grow Room Settings somewhat confusing 

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#35]
To prevent confusion (including my own!), here's some suggested updates to the text within the Settings tab on the Dashboard page:

1. Change "Climate Threshold" to:

"Climate Thresholds: These values determine the CONDITIONS metric on the dashboard. For example, if the last hours' conditions were all within the ranges set here, then CONDITIONS would display as 100%." [This assumes that the CONDITIONS metric is calculated based on values from the last hour]

2.Change "Fans" to:

"Fans: The fans will turn on if the temperature or humidity rises above these values. The fans will remain on until the temperature and humidity falls below these values. `Run Duration` is..."

**Comment by fruxefarms** [comment]
Better clarification! Will amend!
