### ISSUE TITLE
UI On/Off switch-- language is reversed?

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#36]
On Technical » Pump

The "Manual Controls" language isn't consistent with the slider switch.

Changing the label from `"On/Off"` to `"Off/On"` seems better to me.

Also, it would be good to change this on the other controllable items, so the change is needed on:

- Lights
- Fans
- Pump

**Comment by fruxefarms** [comment]
Ahh yes, I see what you mean. Good point!
