### ISSUE TITLE
Pump Manual Control reverts to "ON" after schedule save

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#37]
After clicking the `Save Schedule` button on the `Technical » Pump` page, the `Manual Controls` slider changes to the `ON` position. I don't think that should happen.

**Comment by fruxefarms** [comment]
Is it possible you have two GPIO pins set the same (eg. Lights and Pumps both on BCM 17)? On the page refresh it will poll the current activation state from the GPIO pin. 

Perhaps some more lead up to this error would help. I'm having trouble replicating it.
