### ISSUE TITLE
Dashboard Not Updating

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#38]
After my fresh install today, the temp and humidity values on the Dashboard are not updating. They are stuck at 23 C and 72% humidity. 

In addition, the chart isn't updating.

The sensor diagnostic returns "all good."

BTW, I think this problem began after I install the updates from a couple days ago -- so it is probably not an issue with the most recent updates.

**Comment by dcaud** [comment]
I did another re-installation a couple hours ago. Now the chart is not updating, but the dashboard values are updating.

**Comment by dcaud** [comment]
Great news! I updated to the latest commit (9bc3322) and the chart updated just after the install. A new timestamp on the the x-axis now reads `Apr 2 19:17`. And then a subsequent set of points was plotted at `Apr 2 20:00` This is the first time I can remember the chart updating in the last few weeks (without manual changes). Such good news. 

One small issue, the time stamp is reading one hour behind my local time. That is, although it is 21:22 here, the latest timestamp is 20:00.

**Comment by fruxefarms** [comment]
That's great! The timestamp will always be an hour behind (If i'm understanding you correctly) as the 21:00 CRON collects the hourly average for all temperature/humidity for 20:00 hr, all 21:00 hr data will be reported at 22:00, etc.

That being said, I'm curious your interpretation as perhaps I am way off in how this should be represented.

**Comment by dcaud** [comment]
Ah yes, I think I see where you are coming from with the timestamp. Our different interpretations seem to be about rounding up vs. rounding down.

One way to make this more clear would be to make the time value the **range** that is averaged. For example: `Apr 03 21:00` would become `Apr 03 20 - 21:00`, but that may take up too much screen real estate.

(Also, as I know you know, I really like the idea of flipping the x-axis so that values on the right represent later times.)

But really, the main thing I am happy about is the chart now updates automatically!!!
