### ISSUE TITLE
Camera Not Working

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#39]
Clicking `Take Photo` does not result in a photo -- instead, the small icon for a broken image appears.

Clicking `Test Sensor` results in the grey bar appearing, but no text displays.

When I type `pi@raspberrypi:~ $ raspistill -o cam.jpg` on the command line a photo is saved...so the camera appears to work on my machine.

**Comment by fruxefarms** [comment]
Ah shit! I upgraded the Pillow (Python Imaging Library) to accommodate the PiZero compatibility upgrade and it looks like it is throwing this error again. I will downgrade again and maybe find a happy medium that works for both. So far Pillow 2.2.0 is the only one I can get working, but it has issues with some armhf libraries.

**Comment by fruxefarms** [comment]
Camera issue has been solved in latest commit.
