### ISSUE TITLE
Fans Not Following Schedule

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#40]
I'm not exactly sure how this the fan "scheduler" is supposed to work, but...

I enabled the fans. The fans go on and off with `Manual Controls`. Great!

But the fans either: 1) don't turn on, or 2) turn on each minute for about 17 seconds and then turn off. Whether 1 or 2 happens depends on my settings... I realize this is vague... I plan to troubleshoot more, but I'm out of time at the moment.

**Comment by dcaud** [comment]
I doubt this is it, but maybe it hints at a problem? The color coding on GIT for FruxePi/app/application/views/technical/fans.php changes at line 76 -- maybe an html tag isn't correct?

**Comment by fruxefarms** [comment]
Hmm, let me check on this. I was manually testing the pump and fans from the fruxepi.py CLI script over the weekend. My most alarming discovery is the duration is somehow now in seconds. So an input 5 would run for 5 seconds, not minutes. I haven't fixed that yet.

**Comment by dcaud** [comment]
I'm still looking into the behavior of the fans in the current commit, but here's the goal in my case (and I presume others with greenhouses would have similar goals):

Pull in cooler air from outside of the greenhouse when it gets too hot inside the greenhouse. It can get very hot in the greenhouse, within minutes, when the sun is shining full. The average day will have the fans running about 12 hours straight -- from an hour or so after sunrise to just about sunset. The fans would run more when it is extra hot outside and less when it is cloudy, windy, and extra cool. The temperature threshold seems to be a perfect way to make the fan turn on and off. 

I bring this up because I'm not sure about the fan logic goals in FruxePi, especially the `Run Duration`. One reason to have a run duration is that the fan could unnecessarily cycle on and off quickly if the temperature fluctuates around the threshold setting. Maybe that is the goal of `Run Duration`?

Can you let me know if the intention of FruxePi is something different or if my goals can be accommodated?!

**Comment by fruxefarms** [comment]
You are correct, the `Run Duration` was devised to reduce power flickering due to data sensitivity. I admit, it's a bit primitive. I also thought of some sort of buffer. From a real world perspective, what would an acceptable temperature\humidity range to buffer any wild data? If the intention is that fans run quite regularly perhaps that's a non issue.

**Comment by dcaud** [comment]
1 degree Celsius or 2 degrees Fahrenheit.

Humidity in the greenhouse often spikes relatively quickly to 100% (it may go from 40% to 100% in less than an hour) -- this is because 1) a misting irrigation system and 2) condensation due to significant temperature differentials between inside and out. That said, maybe 3% humidity would be good.

My guess is those ranges would prevent power flickering faster than 2 minutes, which I think would not prevent most unnecessary stress on the fans.

Does that answer your question?

BTW, here's my temp/humidity chart for the last 24 hours:


![Screen Shot 2019-04-07 at 3 28 33 PM](https://user-images.githubusercontent.com/28665108/55688766-89735600-594a-11e9-84a8-fd143e522d62.png)

Notice that trends are usually consistently up or down, which would prevent any power flickering. However, three considerations are necessary:

1. These are hourly averages! Those averages may hide up/down fluctuations within an hour.
2. Notice that the average temp didn't vary between 12:00 and 13:00...this is when power flickering would occur without some management of it (and if the threshold was 24 degrees in this example). 
3. Not all days are like this!

**Comment by fruxefarms** [comment]
The fan program has been tweaked in the upcoming release.
