### ISSUE TITLE
Unexpected Power Failure Caused App to Stop Updating

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#42]
The power to my Raspberry Pi was cut off and on unexpectedly today. After the reboot, the temp/humidity and the chart stopped updating. Can anything be done to make a power failure not cause havoc? Or is a sequence of things possible to do to recover settings and data?

Maybe I'm dreaming again, but my Pi is outside in the greenhouse, and this kind of thing will happen, unfortunately.

**Comment by dcaud** [comment]
SQL server seems to be running. 

A `SELECT * FROM grow_data` shows that the database stopped updating after the power failure...but otherwise seemed to be working. Maybe this is a cron issue?

**Comment by dcaud** [comment]
Cron didn't seem to start again after the reboot, but when I restarted cron, FruxePi seems to be working again! Here's what I did:

```
root@asdf:/# service cron status
[FAIL] cron is not running ... failed!
root@asdf:/# service cron start
[ ok ] Starting periodic command scheduler: cron.
root@asdf:/# service cron status
[ ok ] cron is running.
root@asdf:/# 
```

**Comment by fruxefarms** [comment]
I will expedite the CRON restart issue. I've seen this issue pop up but haven't had the time to fully test and configure.

**Comment by fruxefarms** [comment]
I believe this has been fixed in the latest commit.
