### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#43]
After I enter the login screen (where I entered the default username and password), I get the following:

```
FruxePi » A Database Error Occurred
Error Number: 1146

Table 'frx_db.users' doesn't exist

SELECT `email`, `email`, `id`, `password`, `active`, `last_login` FROM `users` WHERE `email` = 'hello@fruxe.co' ORDER BY `id` DESC LIMIT 1

Filename: models/Ion_auth_model.php

Line Number: 1038
```

I re-updated twice, today, after the latest commit (f6781fa) and the same error occurred

**Comment by fruxefarms** [comment]
I might suggest a hard removal and reset https://docs.fruxe.co/#/update

Particularly, using `sudo docker system prune -a --volumes` as their was some changes to the DB as well.

**Comment by dcaud** [comment]
I'm still getting the same error.

**Comment by fruxefarms** [comment]
Ah damn. There may have been a bad DB field. Try again.

**Comment by dcaud** [comment]
Ok. Trying now.

**Comment by dcaud** [comment]
It worked! I am able to login and I'm no longer getting that error.

Thanks!
