### ISSUE TITLE
Unable to configure Docker images

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#44]
The install bash script gave this error:

```
pi@raspberrypi:~/FruxePi $ sudo bash install.sh

FruxePi v0.2-BETA Install
version: frx-pi-v0.2-BETA
web: docs.fruxe.co

Getting Latest Updates...
Installing required packages..
Building Docker containers... This will take several minutes.
Configuring Docker containers...
Error! Unable to configure Docker images.
```

This only occurred on one of my Raspberry Pi's (the other one has the login error at the moment, but the installation occurs without this error).

I've checked for differences in the OS and done updates of the OS and packages, but I still get the install error. 

I looked for differences between my two Pi's using the following commands and found no differences. Both machines look the same, according to these commands:

`lsb_release -a`
Description:	Raspbian GNU/Linux 9.8 (stretch)

`hostnamectl`
Linux 4.14.98-v7+

And to see if disk space was a problem:
`df -h`
(this showed more than 20 gb of available space) 

`cat /sys/firmware/devicetree/base/model`
Raspberry Pi 3 Model B Plus Rev 1.3

`docker version`
Version:           18.09.0

One difference is that they are on different wifi networks, but I'm not able to test across on both.

**Comment by dcaud** [comment]
FYI, The error above occurred again with the latest commit, with the ARMv7 containers:

```
FruxePi v0.2-BETA Install
version: frx-pi-v0.2-BETA
web: docs.fruxe.co

Getting Latest Updates...
Installing required packages..
Building Docker containers... This will take several minutes.
Deploying Raspberry Pi 3 (ARMv7) compatible containers...
Configuring Docker containers...
Error! Unable to configure Docker images.
```

**Comment by fruxefarms** [comment]
Can you run this `sudo bash install.sh -log` and send again please. I just added this parameter to show/hide logging.

**Comment by dcaud** [comment]
It looks like `sudo: docker-compose: command not found` came up:

```

FruxePi v0.2-BETA Install
version: frx-pi-v0.2-BETA
web: docs.fruxe.co

Getting Latest Updates...
Installing required packages..
Building Docker containers... This will take several minutes.
Deploying Raspberry Pi 3 (ARMv7) compatible containers...
sudo: docker-compose: command not found
Configuring Docker containers...
Error! Unable to configure Docker images.
```

**Comment by fruxefarms** [comment]
I'm curious why docker-compose is all of a sudden absent. Once you have it, there is no need to reinstall.

**Comment by dcaud** [comment]
I guess I never installed it on this new machine. Is it something that would be good to install via the install.sh script? Or should I just manually install it now?

**Comment by fruxefarms** [comment]
I was hoping to install it via the script for ease of use, but this is an issue a few users have reported to me via email as well. I'm thinking it might be prudent to make it a prerequisite and manually install Docker and Docker Compose. 

I have been directing people to this link for troubleshooting:
https://www.bargelt.com/setting-up-a-headless-raspberry-pi-with-ssh-docker-docker-compose-git/

**Comment by Enri2077** [comment]
I also had this problem, the installation finished normally once I installed `sudo apt install docker-compose`.
I suggest mentioning this problem in the [easy installation guide](https://github.com/fruxefarms/FruxePi#easy-install).

**Comment by fruxefarms** [comment]
Definitely making the suggested changes @Enri2077. Will be coming shortly! Thanks for your contribution! :)

**Comment by SeaSlash** [comment]
Thank you. That fixed my issue. As mentioned - would be great to have this in the install guide.

**Comment by fruxefarms** [comment]
Hi @SeaSlash what model of RPi are you running? It seems like the PiZero on Stretch is giving the most grief for Docker. Is this the case?

**Comment by SeaSlash** [comment]
@fruxefarms I'm not the most technical but I'm using the 3 B+ with the pre-loaded software on CanaKit's SD card(NOOBS) -Debian Stretch. Let me know if you need more information & thank you for this great software. I can't wait to more things to get added!

**Comment by edjjoy-code** [comment]
I am also having this issue, and the recommended fix still results in an error.

Fresh Raspbian installation off of SD card with NOOBS, here is the -log output:


version: frx-pi-v0.3-BETA
web: docs.fruxe.co

Getting Latest Updates...
Installing required packages..
Building Docker containers... This will take several minutes.
Deploying Raspberry Pi 3 (ARMv7) compatible containers...
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
Configuring Docker containers...
Error! Unable to configure Docker images.
pi@raspberrypi:~/FruxePi $


Going to wipe/reinstall OS and re-try installation script, however will try and setup Docker manually first?

**Comment by CutsoDave** [comment]
Fresh pi install.  Have tried installing docker-compose before running install.sh.  Have tried multiple memory cards.   Same error.

Tried running through the docker section of - https://www.bargelt.com/setting-up-a-headless-raspberry-pi-with-ssh-docker-docker-compose-git/

Are there other steps I can try?


-log below.

pi@raspberrypi:~/FruxePi $ sudo bash install.sh -log

FruxePi v0.3-BETA Install
version: frx-pi-v0.3-BETA
web: docs.fruxe.co

Getting Latest Updates...
Installing required packages..
Building Docker containers... This will take several minutes.
Deploying Raspberry Pi 3 (ARMv7) compatible containers...
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
Configuring Docker containers...
Error! Unable to configure Docker images.

**Comment by fruxefarms** [comment]
Hmmm, have not encountered this before. Will attempt to reproduce and advise. Thank you!

**Comment by mkono87** [comment]
Im facing this problem on a fresh raspbian buster install on pi3.

**Comment by lucvank** [comment]
This is the solution i used 
https://www.freecodecamp.org/news/the-easy-way-to-set-up-docker-on-a-raspberry-pi-7d24ced073ef/
After commands on this page again i used the original install command in the Fruxe directory and all works fine

**Comment by jhdl123** [comment]
Having the same issue on 3+ .. tried all solutions above but no help . Fresh installed twice

**Comment by mkono87** [comment]
Dead project. I just integrated my grow stuff into my current home assistant setup.

**Comment by jhdl123** [comment]
> Dead project. I just integrated my grow stuff into my current home assistant setup.

What could you suggest to a real noob.... Looking for a gui to run a camera, dht22 and soil hygrometer.

**Comment by mkono87** [comment]
> > Dead project. I just integrated my grow stuff into my current home assistant setup.
> 
> What could you suggest to a real noob.... Looking for a gui to run a camera, dht22 and soil hygrometer.

I think home assistant works great and you might end up doing the rest of your house. lol Overall everything easy to add you just have to do a bit a reading. HA can be installed to a raspberry pi.
