### ISSUE TITLE
Temp and Humidity Values -- Constraining Extreme Values 

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#45]
Hi! 

Sometimes, the DHT22 gives wildly inaccurate readings. This seems to be caused by the hardware of the DHT22...especially in the case of humidity. This is usually momentary and it returns to normal ranges quickly. The problem is that the values can be so high that it throws off the hourly average -- for example, one hour shows an impossibly high relative humidity of 123%.

A simple way to handle this may be to use `median` instead of `mean` for calculating the hourly temp and humidity "central tendency." 

Another way would be to constrain the range for each `fetch`. Although this could make troubleshooting difficult, it would also serve to unnecessarily switch off/on fans. I think I prefer this approach, although I'm not certain how best to constrain the range.

What do you think?

**Comment by fruxefarms** [comment]
I completely agree! I have seen some weird data returned as well. Some simple data scrubbing should fix that. Will also see about returning the median temperature.
