### ISSUE TITLE
Round Fahrenheit in Dashboard AND Elsewhere

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#47]
At the top of the dashboard page, Fahrenheit reads to two decimal places, e.g., 72.43. I think rounding to 0 decimal places is better.

Also, in the Fans page, the temp setting reads to 8 or 9 decimal places (e.g., 69.9999999) after I type in, e.g., 70.

**Comment by fruxefarms** [comment]
The rounding has been a little wild. I've been meaning to fix this. Will prioritize and amend!

**Comment by fruxefarms** [comment]
This has been fixed. Will be addressed in an upcoming push to the Master branch.
