### ISSUE TITLE
Si7021 Sensor 

### ISSUE THREAD

**Issue by PhatCatStinker** [fruxefarms/FruxePi#48]
I was wondering if it was possible to use Si7021 sensor instead of the dht22 sensor.

**Comment by fruxefarms** [comment]
Short answer no, however, perhaps you could try modifying `app/actions/fruxepi.py` in the following way:

At the top of the file with the other imports please add:

```
import smbus
```

Find and replace this code in the `# Return Raw Temperature` function:

```
...
        # Return Raw Temperature
        elif action_option == "-tr":
            fetchRawTemperature(action_GPIO=False)
...
```

Lastly, find the `#Fetch Temperature` function and replace with this:

```
...
# Fetch Temperature
def fetchRawTemperature(gpioPIN):
    try:
        # Get I2C bus
        bus = smbus.SMBus(1)
        bus.write_byte(0x40, 0xF5)
        
        time.sleep(0.3)
        
        # SI7021 address, 0x40  Read 2 bytes, Humidity
        data0 = bus.read_byte(0x40)
        data1 = bus.read_byte(0x40)
        
        # Convert the data
        humidity = ((data0 * 256 + data1) * 125 / 65536.0) - 6
        
        time.sleep(0.3)
        bus.write_byte(0x40, 0xF3)
        time.sleep(0.3)
        
        # SI7021 address, 0x40 Read data 2 bytes, Temperature
        data0 = bus.read_byte(0x40)
        data1 = bus.read_byte(0x40)
        
        # Convert the data and output it
        celsTemp = ((data0 * 256 + data1) * 175.72 / 65536.0) - 46.85

        if temperature is not None:
            data_output = str(round(celsTemp, 2)) + "*C"
            print(data_output)
            return data_output
        else:
            print('Failed to get reading. Try again!')
    except:
        print("Sensor Error!")
    
...
```
Afterwards, reboot your Raspberry Pi for CRON tp start again. The Dashboard should update automatically if this function is replaced, however your can manually test if that sensor works with the FruxePi Dashboard by running these commands from Terminal:

```
docker exec -it frxpi-APACHE /bin/bash
python /var/www/html/actions/fruxepi.py climate -tr

```

Curious to hear your success! If it works, I will modify the fruxepi.py script further.

I based this on some quick code I found [here](http://www.pibits.net/code/raspberry-pi-si7021-sensor-example.php).

**Comment by PhatCatStinker** [comment]
Thanks for the response!

I plugged in the code and do get a value for temp but it’s not right it’s 1136, so it’s very high. Nothing for humidity came up though.

**Comment by fruxefarms** [comment]
Okay, hmm. Just confirming: Are you connected SDA (Physical Pin 3) and SCL (Physical pin 5) on your Pi GPIO?

**Comment by PhatCatStinker** [comment]
Thanks for your help, I have double checked the pinout and it all is correct. But no readings available.

**Comment by fruxefarms** [comment]
I'm afraid I may not be able to effectively troubleshoot this for you. If you do find some code, modifying the `fetchRawTemperature()` and `fetchRawHumidity` methods in `app/action/fruxepi.py` would make this script work. Unfortunately without this sensor to test locally it's really a difficult process. I was hoping it was an easy as implementing the DHT22 library from Adafruit.
