### ISSUE TITLE
Camera Button Disappears after adding User

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#49]
After 0.3 update I saw the new camera button. And it worked beautifully. Then, I added a new user — with an email address as a username and a password. The camera button was then not present. Can you replicate that issue?

**Comment by fruxefarms** [comment]
That is very strange. I followed the procedure several times and no success replicating the issue. It is very puzzling because the only logic attached to that button is whether the camera is activated or not. An overlap seems very strange. However I did find one small bug in this release that I have fixed and will push out later today. Perhaps after that fix on a new install all will be well.

**Comment by dcaud** [comment]
I think I've figured out the problem. It does NOT have to do with adding a user...as I said previously. Sorry for that wild goose chase. 

The view button disappears if you delete the default crop. This is happening because the button is inside the Crops Carousel!

**Comment by fruxefarms** [comment]
Ah yes, that makes sense. That is the way it is supposed to work (whether helpful or not). Adding any crop back and the button will return. However, now I'm thinking that should be changed to display regardless of the crop.

**Comment by dcaud** [comment]
Now that I understand how it works, I can keep a crop. It looks a little
odd because I don't use the crop feature so I have a crop names "_" with a
set of random dates and such.

No big deal, but would it be easy (and a good idea) to move it to the space
above...in the banner area or somewhere else?

**Comment by fruxefarms** [comment]
I think that's entirely reasonable to have the camera separate. It shouldn't be dependent on the crop (and who says the Crop feature is even useful for some). Great feedback!

**Comment by fruxefarms** [comment]
In the latest commit I changed the code to display the button without a crop being present.

**Comment by dcaud** [comment]
Excellent. Works like a charm!
