### ISSUE TITLE
Paths do not match installation instructions?

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#5]
I'm trying to troubleshoot the following error when I try to the Fruxe frontend via a web browser (currently I receive a an error like: "192.168.2.19 refused to connect."). 

One thing I noticed is that the directory structure didn't exactly match the installation structure.

Of note, I located database.php file in this folder:

/var/www/html/application/config 

Whereas the installation instructions said it would be here:

/frx-pi/application/config/

On my machine, I don't seem to have that path.

**Comment by fruxefarms** [comment]
You are correct, this was a documentation error. The correct path is /var/www/html/application/config. The documentation has been amended.
