### ISSUE TITLE
Raspi Zero W - after reboot no server

### ISSUE THREAD

**Issue by Rushmonk** [fruxefarms/FruxePi#52]
I've succesfully installed Fruxe, could click on anything and it was working like a charm.
But after a reboot, the HTML site isn't accessable anymore "Connection refused".
Was testing this serveral times, could you please check this on a Zero W?

Per-installed: git, vim, python-pip, docker.

**Comment by fruxefarms** [comment]
Hmm, it really sounds like your IP changed after the reboot. The Docker containers are set to restart upon boot. 

You can scan your network using `nmap` to find your RPi:
```
apt-get install nmap
nmap -sP 192.168.0.1/24
```

**Comment by Rushmonk** [comment]
Hi, that's what I thougt too, but as I'm still connected via SSH (just re-start the session) the IP address remains the same.

**Comment by fruxefarms** [comment]
Ahh, so perhaps Docker is not running. This will boot Docker if it is not running (I think?):
```
docker ps -a
```
Restarting the Docker containers if they are not running:
```
docker restart frxpi-APACHE frxpi-PHPMYADMIN frxpi-MYSQL
```
Hope this helps!

**Comment by Rushmonk** [comment]
I'm currently reinstalling, will report as soon as it's completed.

**Comment by Rushmonk** [comment]
Hi, I've seen you added now the docker installation, but it's not working. After the installation I've got the error:

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error! Unable to configure Docker images.

Starting manual gives me: 

sudo dockerd
Segmentation fault

Any thoughts?

**Comment by fruxefarms** [comment]
There's definitely an issue with Docker. In the meantime, I will run some tests on a ZeroW and report back with further insight.

**Comment by Rushmonk** [comment]
Hi, I managed to get Docker installed on the Zero W, seems like it's not supported anymore, but there is a workaround. Unfortunately your skript isn't working, it gives me an error:

Getting Latest Updates...
Installing required packages..
Building Docker containers... This will take several minutes.
Deploying Raspberry Pi Zero (ARMv6) compatible containers...
Configuring Docker containers...
Error! Unable to configure Docker images.

But the Docker (daemon and service) is operational:

pi@raspberrypi:~/FruxePi/FruxePi-master $ sudo systemctl status docker.service
 docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: active (running) since Fri 2019-05-17 12:30:31 BST; 4min 40s ago
     Docs: https://docs.docker.com
 Main PID: 438 (dockerd)
      CPU: 22.316s

I'm currently using docker version 18.06.1-ce and locked it to this version, so there will be no update.
Hope this is helping.

**Comment by fruxefarms** [comment]
I think we figured out the issue. We found success installing this version:
```
sudo apt-get -y install docker-ce=18.06.2~ce~3-0~raspbian
```
Doing further testing today and adjusting the install script. Will push the update shortly!

**Comment by fruxefarms** [comment]
I believe this was sorted out in the latest commit. Did fresh installs of Stretch Lite on RPi ZeroW and RPi 3 B+ and all worked famously! I hope you have success, please let me know if it works.

**Comment by fruxefarms** [comment]
I may have spoke too soon. The install issue is fixed, however upon power failure I encountered the same error. I removed the Docker containers and ran the install again and everything is back online, but still not sure the real cause at this point.

**Remove Docker Containers**
```
sudo docker rm -f frxpi-APACHE frxpi-PHPMYADMIN frxpi-MYSQL
```
**Run install script again**
```
sudo bash install.sh -log
```

**Comment by Rushmonk** [comment]
Will test and report asap, thanks for the update!

**Comment by Rushmonk** [comment]
Still the same issue, after sudo reboot, no access anymore.

**Comment by Rushmonk** [comment]
Tested on RPi 3B+ working all ok btw.
But I encountered an new issue, opened a request already.
