### ISSUE TITLE
No Temperature or Humidity readings

### ISSUE THREAD

**Issue by PhatCatStinker** [fruxefarms/FruxePi#53]
Fruxe Pi is installed I have a DHT22 sensor but not getting any temperature or humidity readings.

**Comment by dcaud** [comment]
What have you done to troubleshoot? One thing may be that you have not wired it correctly.

**Comment by PhatCatStinker** [comment]
I have checked my wiring it looks good, I have an rpi3b+ the sensor has 3 pin outs, and “S” , “+” , “-“ so the “S” is the signal I’m guessing and that’s going to physical pin 3. The “+” goes to the 5v pin which is physical pin 1. And the “-“ is the ground and I have that on physical pin 9. I can think of anything else?

**Comment by dcaud** [comment]
I would check the output in Python, using instructions from a web search to make sure you have it wired correctly.

**Comment by fruxefarms** [comment]
Try running this from the Terminal. Perhaps it will throw an error for you. It could also be that Adafruit DHT library is missing or having an issue. 

SSH into Apache Docker container:
```
docker exec -it frxpi-APACHE /bin/bash
```
Fetch temperature reading:
```
python /var/www/html/actions/fruxepi.py climate -t 2
```

**Comment by PhatCatStinker** [comment]
Ok I have reinstalled everything and purchased a new sensor and I am getting a reading for temperature. It is 614.4 but no humidity reading. Any thoughts, i followed the instructions above.

**Comment by dcaud** [comment]
High temp may be due to feeding the sensor wrong voltage (maybe 3 instead of 5), mis-wiring, or wrong sensor model. I’d check wiring first.

**Comment by PhatCatStinker** [comment]
I guess it could be the sensor I am using a DHT11 sensor, from my understanding this sensor is just less accurate to the DHT22 sensor.

**Comment by fruxefarms** [comment]
I suspect sensor also.
