### ISSUE TITLE
Unable to change user password or create new admin

### ISSUE THREAD

**Issue by mrfunk** [fruxefarms/FruxePi#55]
I'm unable to change defalt user password or create new admin..I get 
"The form did not pass our security checks "

When trying to delete a user, I get a 404..thanks

**Comment by fruxefarms** [comment]
Will look into this right away!

**Comment by mrfunk** [comment]
Thanks, and good job so far

**Comment by fruxefarms** [comment]
This issue has been fixed with the latest commit.
