### ISSUE TITLE
Delete activity on new crop? 

### ISSUE THREAD

**Issue by mrfunk** [fruxefarms/FruxePi#58]
There doesn't appear to be a way to remove the app added activity when creating a new crop. Every time I create a new crop, activity already has text in it.

Thanks

**Comment by fruxefarms** [comment]
Yes, this is an area that needs some attention. Now I'm thinking to remove the dummy data from the beginning. That really was just there to demonstrate the crop activity ability. That interface definitely needs a bulk delete function.

**Comment by mrfunk** [comment]
Please, just remove the dummy data, thanks
