### ISSUE TITLE
Dashboard login fails with default UID and Password

### ISSUE THREAD

**Issue by jkissner** [fruxefarms/FruxePi#6]
When attempting to log into the dashboard it cycles and doesn't log in no matter what is put into the UID and password fields. No errors or messages are present.  
I have verified in the DB that the correct email is present.  I also pulled the hash and verified that it matches with the password provided.

**Comment by fruxefarms** [comment]
The documentation lists the default user "hello@fruxe.com" which is incorrect and has now been fixed. It should be "hello@fruxe.co" which is what is represented in the /db/frx_db.sql file. Such a silly mistake on my part. I hope that helps!

**Comment by jkissner** [comment]
You can close this! As the solution resolved it.  Sorry I missed the spelling error in the DB.

**Comment by fruxefarms** [comment]
@jkissner I think the typo is totally my fault. Sorry for any frustration! Great we got it resolved!
