### ISSUE TITLE
Order of installing DB structure is too early?

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#7]
I think the following line in the instructions come too early:

`sudo mysql -u frxpi -p frx_db < /var/www/html/db/frx_db.sql`

As is, the file (frx_db.sql) being used to populate the database is not on the local system until something like the following is complete:

`cd ~
wget https://github.com/fruxefarms/FruxePi/archive/master.zip
sudo unzip master.zip
sudo mv  -v ~/FruxePi-master/* /var/www/html/
sudo rm -rf FruxePi-master master.zip /var/www/html/index.html`

**Comment by fruxefarms** [comment]
Yes, you are absolutely correct! I think this got rearranged by mistake. Will amend! :)
