### ISSUE TITLE
What to choose for "Configure database for phpmyadmin with dbconfig-common?"

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#8]
The dialog came up and the options were yes and no. What's the best response?

**Comment by fruxefarms** [comment]
This is a question I would also like to know! I think I recklessly choose "Yes" without thinking.. Any thoughts?

**Comment by dcaud** [comment]
I did some searching and only found install instructions that said "Yes" is the best response:

1. [https://www.ostechnix.com/install-phpmyadmin-with-lamp-stack-on-ubuntu-16-04/](url)
2. [https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-16-04](url)

I think if "Yes" works, then let's trust it for now!

I'm cool with closing this issue unless you want a more definitive answer!

**Comment by fruxefarms** [comment]
I agree, I think "Yes" is the safe bet for now. I will add this clarification to the README and close the issue when it's updated! Many thanks!
