### ISSUE TITLE
The NON-ISSUE...Thanks for creating FruxePi!

### ISSUE THREAD

**Issue by dcaud** [fruxefarms/FruxePi#9]
I just wanted to say thanks for creating this...even in the beta phase (and although I've yet to make it work), it has given me some great ideas. 

Let me know if you'd like some specific help. Otherwise, I'll just keep chugging away and trying to make it work and suggesting what I think are improvements.

Salud, Jay-yeo, and the rest of the good folks!

[Sorry to put this as an "Issue," but I don't know where this kind of thing should go.]

**Comment by fruxefarms** [comment]
Thank you! I would love your contributions. At the moment many of the issues coming back from users are surrounding the "Launch Barrier" (I think you described it perfectly). This is usually the result of poor documentation (yes I admit wholeheartedly) and some config or permissions issues I suspect. Your efforts are already amazing and are a very positive contribution to perfecting the FruxePi for many more to enjoy!
